### ISSUE TITLE
AccesViolationException

### ISSUE THREAD

**Issue by Sko11** [Da-Teach/Questor#100]
Every time when I start questor I get this message.

Exception during event execution: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

   at . . (IntPtr , IntPtr , IntPtr )

   at . . (Dictionary`2 , Object[] )

   at . . (Object[] )

   at . . (String , Object[] )

   at DirectEve.DirectSession.get_Now()

   at DirectEve.DirectSession.get_IsReady()

   at Questor.Questor.OnFrame(Object sender, EventArgs e) in c:\questor\Questor\Questor.cs:line 149

   at (Object , Object , EventArgs )

   at DirectEve.DirectEve. (Object , LSEventArgs )

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

What should I do? I didn't change anything...
Thanks for advance!

**Comment by below0isk** [comment]
maybe redownload latest build and recompile.

**Comment by Sko11** [comment]
I did it with the newest version. The problem is the same.
Win7 32bit.. what kind of parameter do you need to indentify the problem?.. Or what sould I try to test?

**Comment by Sko11** [comment]
I had to reinstall the Innerspace. Aaaand it's okay now :)
