### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by GCitizen** [Da-Teach/Questor#7]
When starting up and trying to accept a mission, I'm getting this:

AgentInteraction: Start conversation [Start Mission]
AgentInteraction: Waiting for conversation
AgentInteraction: Replying to agent
AgentInteraction: Waiting for mission
AgentInteraction: Mission enemy faction: Serpentis
Exception during event execution: System.NullReferenceException: Object reference not set to an instance of an object.
   at Questor.Modules.AgentInteraction.CheckFaction()
   at Questor.Modules.AgentInteraction.WaitForMission()
   at Questor.Modules.AgentInteraction.ProcessState()
   at Questor.Questor.OnFrame(Object sender, EventArgs e)
   at (Object , Object , EventArgs )
   at DirectEve.DirectEve.(Object , LSEventArgs )
   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

This is with a fresh checkout from the repository, compiled via MSVC# 2010 express

**Comment by xelj** [comment]
Check http://forum.thehackerwithin.com/yaf_postsm2463_Problems-with-compiling-after-Patch.aspx#post2463

**Comment by rixim** [comment]
add this to your pilot's settings.xml:

factionfittings>
    factionfitting faction="Default" fitting="Default" />
/factionfittings>
