### ISSUE TITLE
Unhandled exception error for Valuedump.

### ISSUE THREAD

**Issue by nwallie** [Da-Teach/Questor#83]
When I attempt to run Valuedump after using Questor for several hours, I get the following error in the console:

Unhandled exception in application.
Outer Exception: System.BadImageFormatException: Invalid assembly file format. (Exception from HRESULT: 0x8013141D)

   at System.Reflection.Assembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, Assembly locationHint, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection)

   at System.Reflection.Assembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, Assembly locationHint, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection)

   at System.Reflection.Assembly.InternalLoad(AssemblyName assemblyRef, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)

   at System.Reflection.Assembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)

   at System.Reflection.Assembly.Load(String assemblyString, Evidence assemblySecurity)

   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, Evidence assemblySecurity, String[] args)

   at System.AppDomain.ExecuteAssemblyByName(String assemblyName)

   at System.AppDomain.ExecuteAssemblyByName(String assemblyName)

   at LavishVMRuntime.LVMDomainManager.AsEx.NewExecuteAssembly2()

   at LavishVMRuntime.LVMDomainManager.AsEx.NewExecuteAssembly()

   at LavishVMRuntime.LVMDomainManager.AssemblyExecuter(Object Obj)

However, If I run it just after logging in, it'll load up fine.
This happens with compiles from the master, experimental and several of the branch's code.

**Comment by nwallie** [comment]
Figured out a way to still use VD from a script.
